import type { Metadata } from "next";
import { Ubuntu, Jost } from "next/font/google";
import "./globals.css";
import { GoogleTagManager } from "@next/third-parties/google";
import AuthProvider from "@/providers/auth-provider";
import ToastProvider from "@/providers/toast-provider";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["500", "700"],
  variable: '--font-ubuntu',
});
const jost = Jost({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: '--font-jost',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <link rel="icon" href="/favicon.ico" />
      <body className={`${ubuntu.variable} ${jost.variable}`}>
        <AuthProvider>
          <ToastProvider />
          {children}
          <GoogleTagManager gtmId="GTM-NQ3HFVFF" />
        </AuthProvider>
      </body>
    </html>
  );
}
